### ISSUE TITLE
Theme T1 make bug with plugin

### ISSUE THREAD

**Issue by Scorpions95** [Eight-P/BD.8P#33]
### T1 Issue report:

When i enable plugin, theme makes bug with icon, i describe everything here
(sorry fo the link) https://github.com/mwittrien/BetterDiscordAddons/issues/2862#event-16096129542

### Discord client:

Stable (Default)

### Discord Mod:

BetterDiscord

### Platform:

Windows

### T1 version:

0.8.2

### Additional notes:

How to reproduce the bug: Download plugin ServerFolder, install and enable it
then active T1 theme

**Comment by Eight-P** [comment]
Should be fixed as with 0.6.72, thanks for letting me know.

**Comment by Scorpions95** [comment]
> Should be fixed as with 0.6.72, thanks for letting me know.

nah, still not fixed

![Image](https://github.com/user-attachments/assets/6ec59443-bec0-42d1-a60a-770359c76394)

**Comment by Eight-P** [comment]
You most likely haven't received the update yet, usually restarting Discord (can also do [ctrl + r] ) takes care of that.
If it doesn't:

Open your User Settings(cog wheel - top left), scroll all the way to the bottom on the left, and tell me what version it shows you.

<sub>Oh, and there is an issue with hiding the server bar using collapsible UI, but I'll have to look at that another time.
The plugin isn't very easy to work with unfortunately.</sub>

**Comment by Scorpions95** [comment]
> You most likely haven't received the update yet, usually restarting Discord (can also do [ctrl + r] ) takes care of that. If it doesn't:
> 
> Open your User Settings(cog wheel - top left), scroll all the way to the bottom on the left, and tell me what version it shows you for the T1-Theme.
> 
> Oh, and there is an issue with hiding the server bar using collapsible UI, but I'll have to look at that another time. The plugin isn't very easy to work with unfortunately.

![Image](https://github.com/user-attachments/assets/753995b4-349e-4c72-81c5-b7b02a65a36b)

**Comment by Eight-P** [comment]
And the server icons are still sideways when you use the ServerFolders plugin?

**Comment by Scorpions95** [comment]
> And the server icons are still sideways when you use the ServerFolders plugin?

Today i check if everything is working fine aand notice it's all good, SO
thank you for your support and thanks for the thame you made, i love it
appriciate ur help and support !
